# Generated by Django 2.2.10 on 2020-02-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200229_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aritcle',
            old_name='isshow_article',
            new_name='show_article',
        ),
    ]
