# Generated by Django 2.2.10 on 2020-02-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200229_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='article_title',
            field=models.TextField(),
        ),
    ]
