# Generated by Django 2.2.10 on 2020-02-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200229_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcle',
            name='modify_time',
            field=models.TimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
