# Generated by Django 2.2.10 on 2020-02-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_aritcle_modify_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aritcle',
            name='modify_time',
        ),
    ]
