# Generated by Django 2.2.10 on 2020-02-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('article', '0007_remove_aritcle_modify_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aritcle',
            name='article_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
