# Generated by Django 2.2.10 on 2020-02-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_aritcle_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='文章类型', to='category.Category'),
        ),
    ]
